records:
  tx_news_domain_model_news:
    
    # if the get parameter is set in the URL the cs_seo properties will be shown
    enable: 'GP:tx_news_pi1|news'

    # if the model already has fields like title etc. define them as fallback
    fallback:

    # cs_seo title field fallback = mymod title field
    title: title

    # cs_seo description field fallback = mymod description field
    description: description
